# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def solve():
    
    limit = 4e6
    term_1 = 1
    term_2 = 2
    result = 2
    
    # Only one in 3 terms are even
    new_term = term_1 + term_2
    condition = new_term <= limit
    even = 0
    while condition:
        even = (even + 1)%3
        if even == 0:
            result += new_term
        term_1, term_2 = term_2, new_term
        new_term = term_1 + term_2
        condition = new_term <= limit
    
    return(result)
    
print(solve())